name: 'Install SQL LocalDB'
description: 'Installs Microsoft SQL Server Express LocalDB 2016 SP2'
runs:
  using: "composite"
  steps:
    - run: | 
        Write-Host "Downloading"
        Import-Module BitsTransfer
        Start-BitsTransfer -Source https://download.microsoft.com/download/4/1/A/41AD6EDE-9794-44E3-B3D5-A1AF62CD7A6F/sql16_sp2_dlc/en-us/SqlLocalDB.msi -Destination SqlLocalDB.msi
        Write-Host "Installing"
        Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
        Write-Host "Checking"
        sqlcmd -l 60 -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
      shell: pwsh
