name: Continuous integration

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build & test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install SQL LocalDB
      - run: | 
          Write-Host "Downloading"
          Import-Module BitsTransfer
          Start-BitsTransfer -Source https://download.microsoft.com/download/7/c/1/7c14e92e-bdcb-4f89-b7cf-93543e7112d1/SqlLocalDB.msi -Destination SqlLocalDB.msi
          Write-Host "Installing"
          Start-Process -FilePath "SqlLocalDB.msi" -Wait -ArgumentList "/qn", "/norestart", "/l*v SqlLocalDBInstall.log", "IACCEPTSQLLOCALDBLICENSETERMS=YES";
          Write-Host "Checking"
          sqlcmd -l 60 -S "(localdb)\MSSQLLocalDB" -Q "SELECT @@VERSION;"
      - name: Build & test Content Definitions
        working-directory: ./src/@episerver/content-definitions
        run: |
          npm ci
          npm test
      - name: Build & test Content Delivery
        working-directory: ./src/@episerver/content-delivery
        run: |
          npm ci
          npm test

