name: Continuous integration

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    name: Build & test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/install-sql-localdb
      - uses: actions/setup-node@v2
        with:
          node-version: 13
      - name: Build & test Content Definitions
        working-directory: ./src/@episerver/content-definitions
        run: |
          npm ci
          npm test
      - name: Build & test Content Delivery
        working-directory: ./src/@episerver/content-delivery
        run: |
          npm ci
          npm test
